default_job = "test"
env.CARGO_TERM_COLOR = "always"

[jobs.clippy]
command = ["cargo", "make", "lint"]
need_stdout = false

[jobs.test]
command = ["cargo", "make", "test"]
need_stdout = true

[jobs.run]
command = [
    "cargo", "make","run"
]
need_stdout = true
allow_warnings = true
on_change_strategy = "kill_then_restart"
background = false

[keybindings]
c = "job:clippy"
