[package]
name = "cli-kneeboard"
version = "0.3.1"
edition = "2021"
license = "MIT"
authors = ["Alexis Lowe <agl314@chimbosonic.com>"]
description = "Checklist Tool"
readme = "README.md"
categories = ["command-line-utilities"]
repository = "https://github.com/chimbosonic/cli-kneeboard"
keywords = ["todo", "git-hook", "markdown", "git", "checklist"]

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
env_logger = "0.11.2"
log = "0.4.20"
pulldown-cmark = "0.10.0"
serde = "1.0.197"
serde_derive = "1.0.197"
toml = "0.8.10"
time = { version = "0.3.34", features = ["serde-well-known"] }

[dev-dependencies]
test-log = "0.2.14"
testing_logger = "0.1.1"

[dependencies.cursive]
version = "0.20.0"
default-features = false
features = ["crossterm-backend"]

[[bin]]
name = "kneeboard"
path = "src/main.rs"

[profile.release]
opt-level = 3
strip = "debuginfo"
lto = true
panic = "abort"
debug = false

# Optimize local dev builds
[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
