[package]
name = "cli-kneeboard"
version = "0.1.4"
edition = "2021"
license = "GPL-3.0-only"
authors = ["Alexis Lowe <agl314@chimbosonic.com>"]
description = "Checklist Tool"
readme = "README.md"
categories = ["command-line-utilities"]
repository = "https://github.com/chimbosonic/cli-kneeboard"
keywords = ["todo", "git-hook", "markdown", "git", "checklist"]

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
env_logger = "0.10.0"
log = "0.4.17"
pulldown-cmark = "0.9.2"
serde = "1.0.149"
serde_derive = "1.0.149"
test-log = "0.2.11"
testing_logger = "0.1.1"
toml = "0.5.9"
time = { version = "0.3.17", features = ["serde-well-known"] }

[dependencies.cursive]
version = "0.20.0"
default-features = false
features = ["crossterm-backend"]

[[bin]]
name = "kneeboard"
path = "src/main.rs"

[profile.release]
opt-level = 3
strip = "debuginfo"
lto = true
panic = "abort"
debug = false
